language: node_js

node_js:
  - '16'
  - '17'

env:
  - NODE_ENV=TEST

cache:
  yarn: true
  directories:
    - 'node_modules'

script:
  - echo "Running tests against $(node -v) ..."
  - yarn test:coveralls

jobs:
  include:
    - stage: deploy
      if: branch == master && !fork
      node_js: '16'
      script:
        - yarn build
        - npx semantic-release
